// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Q7P9E262uIJB_lFSF4VJpzK-fXtF_ZA',
    appId: '1:414055075856:web:424a8527b7ebb040b87a95',
    messagingSenderId: '414055075856',
    projectId: 'app-p-aab03',
    authDomain: 'app-p-aab03.firebaseapp.com',
    storageBucket: 'app-p-aab03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACbWh4xzQcdNWg4ycHGfdWH6O25S9sHis',
    appId: '1:414055075856:android:bfaf6aec6611ae2db87a95',
    messagingSenderId: '414055075856',
    projectId: 'app-p-aab03',
    storageBucket: 'app-p-aab03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe8kSEnSvmRR1WnvhSgvwNas4NNWa5Qak',
    appId: '1:414055075856:ios:055a6be97aaf75a4b87a95',
    messagingSenderId: '414055075856',
    projectId: 'app-p-aab03',
    storageBucket: 'app-p-aab03.firebasestorage.app',
    iosBundleId: 'com.example.appPalmaV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe8kSEnSvmRR1WnvhSgvwNas4NNWa5Qak',
    appId: '1:414055075856:ios:055a6be97aaf75a4b87a95',
    messagingSenderId: '414055075856',
    projectId: 'app-p-aab03',
    storageBucket: 'app-p-aab03.firebasestorage.app',
    iosBundleId: 'com.example.appPalmaV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5Q7P9E262uIJB_lFSF4VJpzK-fXtF_ZA',
    appId: '1:414055075856:web:1a0261c70b7a4815b87a95',
    messagingSenderId: '414055075856',
    projectId: 'app-p-aab03',
    authDomain: 'app-p-aab03.firebaseapp.com',
    storageBucket: 'app-p-aab03.firebasestorage.app',
  );
}